### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by issmile** [hilongjw/vue-zhihu-daily#12]
```
E:\vue\zhihu>npm start

> vue-zhihu-daily@1.0.0 start E:\vue\zhihu
> cd server && node app

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (E:\vue\zhihu\node_modules\.4.14.0@express\lib\applic
ation.js:617:24)
    at Object.<anonymous> (E:\vue\zhihu\server\app.js:25:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

```

**Comment by hilongjw** [comment]
请检查你本地的80端口有没被其他应用占用

**Comment by Pillar-Zhang** [comment]
OK
