### ISSUE TITLE
mac上代码无法运行

### ISSUE THREAD

**Issue by chenjunxyf** [hilongjw/vue-zhihu-daily#20]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.5
3 info using node@v5.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle vue-zhihu-daily@1.0.0~prestart: vue-zhihu-daily@1.0.0
6 silly lifecycle vue-zhihu-daily@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle vue-zhihu-daily@1.0.0~start: vue-zhihu-daily@1.0.0
8 verbose lifecycle vue-zhihu-daily@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle vue-zhihu-daily@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/chenjun/repos/me/vue-demo/vue-zhihu-daily/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle vue-zhihu-daily@1.0.0~start: CWD: /Users/chenjun/repos/me/vue-demo/vue-zhihu-daily
11 silly lifecycle vue-zhihu-daily@1.0.0~start: Args: [ '-c', 'cd server && node app' ]
12 silly lifecycle vue-zhihu-daily@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle vue-zhihu-daily@1.0.0~start: Failed to exec start script
14 verbose stack Error: vue-zhihu-daily@1.0.0 start: `cd server && node app`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid vue-zhihu-daily@1.0.0
16 verbose cwd /Users/chenjun/repos/me/vue-demo/vue-zhihu-daily
17 error Darwin 16.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.0.0
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error vue-zhihu-daily@1.0.0 start: `cd server && node app`
22 error Exit status 1
23 error Failed at the vue-zhihu-daily@1.0.0 start script 'cd server && node app'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-zhihu-daily package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cd server && node app
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-zhihu-daily
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-zhihu-daily
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

npm报错提示如上

**Comment by BarryZhan** [comment]
我也遇上了上述问题

**Comment by hilongjw** [comment]
看起来是这里的问题

```bash
cd server && node app
```
改成这样应该就可以了
```bash
node server/app
```
